### ISSUE TITLE
Does not open func.gii files (from HCP)

### ISSUE THREAD

**Issue by LetiziaClementi** [nno/matlab_GIfTI#3]
I am unable to open file with a func.gii extension, which are the output of a standard routine made available by workbench to extract cortical nodes referring to fMRI data

**Comment by nno** [comment]
Greetings,
the files in this repository may be outdated. I should probably remove it.
Please use the original and latest code: 
- website: https://www.artefact.tk/software/matlab/gifti/
- github: https://github.com/gllmflndn/gifti
I hope that helps.
